"""Report generation orchestrator.

Each report type has a dedicated private method that fetches KPI data
(currently demo data mirroring ``api/v1/kpis.py``), transforms it, and
produces a ``ReportOutput`` containing both structured data and an HTML
representation suitable for PDF rendering.
"""

from __future__ import annotations

import html
from dataclasses import dataclass, field
from datetime import UTC, datetime
from typing import Any

import structlog

log = structlog.get_logger(__name__)


# ---------------------------------------------------------------------------
# Data model
# ---------------------------------------------------------------------------

@dataclass
class ReportOutput:
    """Container returned by every generator method."""

    content_html: str
    content_data: dict[str, Any]
    report_type: str
    generated_at: str = field(default_factory=lambda: datetime.now(UTC).isoformat())


# ---------------------------------------------------------------------------
# HTML helpers
# ---------------------------------------------------------------------------

_CSS = """\
<style>
  body { font-family: 'Segoe UI', Arial, sans-serif; color: #1e293b; margin: 0; padding: 24px; }
  .header { display: flex; align-items: center; gap: 16px; margin-bottom: 24px; }
  .logo { width: 40px; height: 40px; border-radius: 8px;
          background: linear-gradient(135deg, #3b82f6, #8b5cf6); display: flex;
          align-items: center; justify-content: center; color: #fff;
          font-weight: 700; font-size: 18px; }
  .title { font-size: 22px; font-weight: 700; }
  .subtitle { font-size: 13px; color: #64748b; }
  .kpi-row { display: flex; gap: 16px; flex-wrap: wrap; margin-bottom: 24px; }
  .kpi-card { flex: 1 1 180px; border: 1px solid #e2e8f0; border-radius: 10px;
              padding: 16px; background: #f8fafc; }
  .kpi-label { font-size: 12px; color: #64748b; text-transform: uppercase; }
  .kpi-value { font-size: 24px; font-weight: 700; margin-top: 4px; }
  .kpi-trend { font-size: 12px; margin-top: 2px; }
  .trend-up { color: #16a34a; }
  .trend-down { color: #dc2626; }
  table { width: 100%; border-collapse: collapse; margin-bottom: 24px; font-size: 13px; }
  th { background: #1e293b; color: #fff; padding: 10px 12px; text-align: left; }
  td { padding: 8px 12px; border-bottom: 1px solid #e2e8f0; }
  tr:nth-child(even) td { background: #f1f5f9; }
  .footer { margin-top: 32px; font-size: 11px; color: #94a3b8; border-top: 1px solid #e2e8f0; padding-top: 12px; }
</style>
"""


def _wrap_html(title: str, subtitle: str, body: str, generated_at: str) -> str:
    """Wrap report body in a full HTML document with AgenticOrg branding."""
    return (
        "<!DOCTYPE html><html lang='en'><head><meta charset='utf-8'>"
        f"<title>{html.escape(title)}</title>{_CSS}</head><body>"
        f"<div class='header'>"
        f"  <div class='logo'>AO</div>"
        f"  <div><div class='title'>{html.escape(title)}</div>"
        f"  <div class='subtitle'>{html.escape(subtitle)}</div></div>"
        f"</div>"
        f"{body}"
        f"<div class='footer'>Generated by AgenticOrg &middot; {html.escape(generated_at)}</div>"
        f"</body></html>"
    )


def _kpi_card(label: str, value: str, trend: float | None = None) -> str:
    """Render a single KPI card."""
    trend_html = ""
    if trend is not None:
        cls = "trend-up" if trend >= 0 else "trend-down"
        arrow = "&#9650;" if trend >= 0 else "&#9660;"
        trend_html = f"<div class='kpi-trend {cls}'>{arrow} {abs(trend):.1f}%</div>"
    return (
        f"<div class='kpi-card'>"
        f"  <div class='kpi-label'>{html.escape(label)}</div>"
        f"  <div class='kpi-value'>{html.escape(str(value))}</div>"
        f"  {trend_html}"
        f"</div>"
    )


def _table(headers: list[str], rows: list[list[str]]) -> str:
    """Render an HTML table."""
    hdr = "".join(f"<th>{html.escape(h)}</th>" for h in headers)
    body_rows = ""
    for row in rows:
        cells = "".join(f"<td>{html.escape(str(c))}</td>" for c in row)
        body_rows += f"<tr>{cells}</tr>"
    return f"<table><thead><tr>{hdr}</tr></thead><tbody>{body_rows}</tbody></table>"


def _inr(amount: int | float) -> str:
    """Format an Indian-rupee amount with commas."""
    s = f"{amount:,.0f}"
    return f"INR {s}"


# ---------------------------------------------------------------------------
# Generator class
# ---------------------------------------------------------------------------

class ReportGenerator:
    """Orchestrates report generation by dispatching to type-specific methods."""

    _DISPATCH: dict[str, str] = {
        "cfo_daily": "_generate_cfo_daily",
        "cmo_weekly": "_generate_cmo_weekly",
        "aging_report": "_generate_aging_report",
        "pnl_report": "_generate_pnl_report",
        "campaign_report": "_generate_campaign_report",
        "shadow_reconciliation": "_generate_shadow_reconciliation",
    }

    def generate(
        self,
        report_type: str,
        params: dict[str, Any],
        company_id: str = "default",
        tenant_id: str = "default",
    ) -> ReportOutput:
        """Entry point — resolve *report_type* and delegate."""
        method_name = self._DISPATCH.get(report_type)
        if method_name is None:
            supported = ", ".join(sorted(self._DISPATCH))
            msg = f"Unknown report type '{report_type}'. Supported: {supported}"
            raise ValueError(msg)

        method = getattr(self, method_name)
        log.info(
            "report_generate",
            report_type=report_type,
            company_id=company_id,
            tenant_id=tenant_id,
        )
        return method(params, company_id=company_id, tenant_id=tenant_id)

    # ------------------------------------------------------------------
    # CFO Daily
    # ------------------------------------------------------------------

    def _generate_cfo_daily(
        self,
        params: dict[str, Any],
        *,
        company_id: str = "default",
        tenant_id: str = "default",
    ) -> ReportOutput:
        data = self._fetch_cfo_kpis(company_id)
        now_str = datetime.now(UTC).strftime("%Y-%m-%d %H:%M UTC")

        kpis = "".join([
            "<div class='kpi-row'>",
            _kpi_card("Cash Runway", f"{data['cash_runway_months']:.1f} mo", data.get("cash_runway_trend")),
            _kpi_card("Monthly Burn", _inr(data["burn_rate"]), data.get("burn_rate_trend")),
            _kpi_card("DSO", f"{data['dso_days']} days", data.get("dso_trend")),
            _kpi_card("DPO", f"{data['dpo_days']} days", data.get("dpo_trend")),
            _kpi_card("Pending Approvals", str(data["pending_approvals_count"])),
            "</div>",
        ])

        bank_rows = [[b["account"], f"{b['currency']} {b['balance']:,.0f}"] for b in data["bank_balances"]]
        bank_table = _table(["Account", "Balance"], bank_rows)

        tax_rows = [[t["filing"], t["due_date"], t["status"].title()] for t in data["tax_calendar"]]
        tax_table = _table(["Filing", "Due Date", "Status"], tax_rows)

        body = f"{kpis}<h3>Bank Balances</h3>{bank_table}<h3>Tax Calendar</h3>{tax_table}"

        content_html = _wrap_html(
            "CFO Daily Briefing",
            f"Company: {company_id} | {now_str}",
            body,
            now_str,
        )

        return ReportOutput(
            content_html=content_html,
            content_data=data,
            report_type="cfo_daily",
        )

    # ------------------------------------------------------------------
    # CMO Weekly
    # ------------------------------------------------------------------

    def _generate_cmo_weekly(
        self,
        params: dict[str, Any],
        *,
        company_id: str = "default",
        tenant_id: str = "default",
    ) -> ReportOutput:
        data = self._fetch_cmo_kpis(company_id)
        now_str = datetime.now(UTC).strftime("%Y-%m-%d %H:%M UTC")

        kpis = "".join([
            "<div class='kpi-row'>",
            _kpi_card("CAC", _inr(data["cac"]), data.get("cac_trend")),
            _kpi_card("MQLs", str(data["mqls"]), data.get("mqls_trend")),
            _kpi_card("SQLs", str(data["sqls"]), data.get("sqls_trend")),
            _kpi_card("Pipeline Value", _inr(data["pipeline_value"]), data.get("pipeline_trend")),
            _kpi_card("Brand Sentiment", str(data["brand_sentiment_score"]), data.get("brand_sentiment_trend")),
            "</div>",
        ])

        roas_rows = [[ch, f"{val:.1f}x"] for ch, val in data["roas_by_channel"].items()]
        roas_table = _table(["Channel", "ROAS"], roas_rows)

        email_data = data["email_performance"]
        email_rows = [
            ["Open Rate", f"{email_data['open_rate']:.1f}%"],
            ["Click Rate", f"{email_data['click_rate']:.1f}%"],
            ["Unsubscribe Rate", f"{email_data['unsubscribe_rate']:.1f}%"],
        ]
        email_table = _table(["Metric", "Value"], email_rows)

        top_pages = data["content_top_pages"]
        page_rows = [[p["page"], f"{p['views']:,}", f"{p['avg_time_sec']}s"] for p in top_pages]
        pages_table = _table(["Page", "Views", "Avg Time"], page_rows)

        body = (
            f"{kpis}"
            f"<h3>ROAS by Channel</h3>{roas_table}"
            f"<h3>Email Performance</h3>{email_table}"
            f"<h3>Top Content Pages</h3>{pages_table}"
        )

        content_html = _wrap_html(
            "CMO Weekly Report",
            f"Company: {company_id} | {now_str}",
            body,
            now_str,
        )

        return ReportOutput(
            content_html=content_html,
            content_data=data,
            report_type="cmo_weekly",
        )

    # ------------------------------------------------------------------
    # AR/AP Aging Report
    # ------------------------------------------------------------------

    def _generate_aging_report(
        self,
        params: dict[str, Any],
        *,
        company_id: str = "default",
        tenant_id: str = "default",
    ) -> ReportOutput:
        data = self._fetch_cfo_kpis(company_id)
        now_str = datetime.now(UTC).strftime("%Y-%m-%d %H:%M UTC")

        ar = data["ar_aging"]
        ap = data["ap_aging"]

        buckets = ["0-30 days", "31-60 days", "61-90 days", "90+ days"]
        ar_vals = [ar["0_30"], ar["31_60"], ar["61_90"], ar["90_plus"]]
        ap_vals = [ap["0_30"], ap["31_60"], ap["61_90"], ap["90_plus"]]

        ar_rows = [[b, _inr(v)] for b, v in zip(buckets, ar_vals, strict=False)]
        ap_rows = [[b, _inr(v)] for b, v in zip(buckets, ap_vals, strict=False)]

        ar_total = sum(ar_vals)
        ap_total = sum(ap_vals)

        ar_rows.append(["Total", _inr(ar_total)])
        ap_rows.append(["Total", _inr(ap_total)])

        kpis = "".join([
            "<div class='kpi-row'>",
            _kpi_card("Total AR", _inr(ar_total)),
            _kpi_card("Total AP", _inr(ap_total)),
            _kpi_card("Net Position", _inr(ar_total - ap_total)),
            _kpi_card("DSO", f"{data['dso_days']} days"),
            _kpi_card("DPO", f"{data['dpo_days']} days"),
            "</div>",
        ])

        body = (
            f"{kpis}"
            f"<h3>Accounts Receivable Aging</h3>{_table(['Bucket', 'Amount'], ar_rows)}"
            f"<h3>Accounts Payable Aging</h3>{_table(['Bucket', 'Amount'], ap_rows)}"
        )

        content_html = _wrap_html(
            "AR/AP Aging Report",
            f"Company: {company_id} | {now_str}",
            body,
            now_str,
        )

        return ReportOutput(
            content_html=content_html,
            content_data={"ar_aging": ar, "ap_aging": ap, "dso_days": data["dso_days"], "dpo_days": data["dpo_days"]},
            report_type="aging_report",
        )

    # ------------------------------------------------------------------
    # P&L Report
    # ------------------------------------------------------------------

    def _generate_pnl_report(
        self,
        params: dict[str, Any],
        *,
        company_id: str = "default",
        tenant_id: str = "default",
    ) -> ReportOutput:
        data = self._fetch_cfo_kpis(company_id)
        now_str = datetime.now(UTC).strftime("%Y-%m-%d %H:%M UTC")

        pl_data = data["monthly_pl"]

        total_revenue = sum(m["revenue"] for m in pl_data)
        total_cogs = sum(m["cogs"] for m in pl_data)
        total_gm = sum(m["gross_margin"] for m in pl_data)
        total_opex = sum(m["opex"] for m in pl_data)
        total_ni = sum(m["net_income"] for m in pl_data)

        gm_pct = (total_gm / total_revenue * 100) if total_revenue else 0
        ni_pct = (total_ni / total_revenue * 100) if total_revenue else 0

        kpis = "".join([
            "<div class='kpi-row'>",
            _kpi_card("Total Revenue", _inr(total_revenue)),
            _kpi_card("Gross Margin", f"{gm_pct:.1f}%"),
            _kpi_card("Net Income", _inr(total_ni)),
            _kpi_card("Net Margin", f"{ni_pct:.1f}%"),
            "</div>",
        ])

        headers = ["Month", "Revenue", "COGS", "Gross Margin", "OpEx", "Net Income"]
        rows = [
            [m["month"], _inr(m["revenue"]), _inr(m["cogs"]),
             _inr(m["gross_margin"]), _inr(m["opex"]), _inr(m["net_income"])]
            for m in pl_data
        ]
        rows.append(["Total", _inr(total_revenue), _inr(total_cogs),
                      _inr(total_gm), _inr(total_opex), _inr(total_ni)])

        body = f"{kpis}<h3>Profit & Loss Statement</h3>{_table(headers, rows)}"

        content_html = _wrap_html(
            "Profit & Loss Report",
            f"Company: {company_id} | {now_str}",
            body,
            now_str,
        )

        return ReportOutput(
            content_html=content_html,
            content_data={"monthly_pl": pl_data, "totals": {
                "revenue": total_revenue, "cogs": total_cogs,
                "gross_margin": total_gm, "opex": total_opex,
                "net_income": total_ni,
            }},
            report_type="pnl_report",
        )

    # ------------------------------------------------------------------
    # Campaign Performance
    # ------------------------------------------------------------------

    def _generate_campaign_report(
        self,
        params: dict[str, Any],
        *,
        company_id: str = "default",
        tenant_id: str = "default",
    ) -> ReportOutput:
        data = self._fetch_cmo_kpis(company_id)
        now_str = datetime.now(UTC).strftime("%Y-%m-%d %H:%M UTC")

        kpis = "".join([
            "<div class='kpi-row'>",
            _kpi_card("CAC", _inr(data["cac"]), data.get("cac_trend")),
            _kpi_card("MQLs", str(data["mqls"]), data.get("mqls_trend")),
            _kpi_card("SQLs", str(data["sqls"]), data.get("sqls_trend")),
            _kpi_card("Pipeline", _inr(data["pipeline_value"]), data.get("pipeline_trend")),
            "</div>",
        ])

        roas_rows = [[ch, f"{val:.1f}x"] for ch, val in data["roas_by_channel"].items()]

        social_rows = [[platform, f"{engagements:,}"] for platform, engagements in data["social_engagement"].items()]

        traffic = data["website_traffic"]
        traffic_rows = [
            ["Sessions", f"{traffic['sessions']:,}"],
            ["Users", f"{traffic['users']:,}"],
            ["Bounce Rate", f"{traffic['bounce_rate']:.1f}%"],
        ]

        body = (
            f"{kpis}"
            f"<h3>ROAS by Channel</h3>{_table(['Channel', 'ROAS'], roas_rows)}"
            f"<h3>Social Engagement</h3>{_table(['Platform', 'Engagements'], social_rows)}"
            f"<h3>Website Traffic</h3>{_table(['Metric', 'Value'], traffic_rows)}"
        )

        content_html = _wrap_html(
            "Campaign Performance Report",
            f"Company: {company_id} | {now_str}",
            body,
            now_str,
        )

        return ReportOutput(
            content_html=content_html,
            content_data=data,
            report_type="campaign_report",
        )

    # ------------------------------------------------------------------
    # Shadow Reconciliation (weekly system audit)
    # ------------------------------------------------------------------

    def _generate_shadow_reconciliation(
        self,
        params: dict[str, Any],
        *,
        company_id: str = "default",
        tenant_id: str = "default",
    ) -> ReportOutput:
        now_str = datetime.now(UTC).strftime("%Y-%m-%d %H:%M UTC")

        # In production this queries the shadow-mode audit log.  For now,
        # emit a placeholder that confirms the system is running.
        data: dict[str, Any] = {
            "shadow_agents_active": 25,
            "shadow_tasks_evaluated": 1_482,
            "agreement_rate_pct": 96.2,
            "disagreements": 56,
            "escalations": 3,
            "period": "last 7 days",
        }

        kpis = "".join([
            "<div class='kpi-row'>",
            _kpi_card("Shadow Agents", str(data["shadow_agents_active"])),
            _kpi_card("Tasks Evaluated", f"{data['shadow_tasks_evaluated']:,}"),
            _kpi_card("Agreement Rate", f"{data['agreement_rate_pct']:.1f}%"),
            _kpi_card("Disagreements", str(data["disagreements"])),
            _kpi_card("Escalations", str(data["escalations"])),
            "</div>",
        ])

        body = (
            f"{kpis}"
            f"<p>Period: {html.escape(data['period'])}</p>"
            f"<p>All 35 agents ran in shadow mode during the evaluation period. "
            f"Agreement rate is above the 95% confidence threshold.</p>"
        )

        content_html = _wrap_html(
            "Shadow Reconciliation Report",
            f"System audit | {now_str}",
            body,
            now_str,
        )

        return ReportOutput(
            content_html=content_html,
            content_data=data,
            report_type="shadow_reconciliation",
        )

    # ------------------------------------------------------------------
    # KPI data fetchers (demo data — production will call internal APIs)
    # ------------------------------------------------------------------

    @staticmethod
    def _fetch_cfo_kpis(company_id: str) -> dict[str, Any]:
        """Return CFO KPI data.  Mirrors ``api/v1/kpis.py`` demo payload."""
        return {
            "cash_runway_months": 14.2,
            "cash_runway_trend": 1.8,
            "burn_rate": 18_50_000,
            "burn_rate_trend": -3.2,
            "dso_days": 42,
            "dso_trend": -5.1,
            "dpo_days": 38,
            "dpo_trend": 2.4,
            "ar_aging": {
                "0_30": 32_00_000,
                "31_60": 14_50_000,
                "61_90": 6_80_000,
                "90_plus": 2_10_000,
            },
            "ap_aging": {
                "0_30": 22_00_000,
                "31_60": 9_50_000,
                "61_90": 3_20_000,
                "90_plus": 80_000,
            },
            "monthly_pl": [
                {"month": "2026-01", "revenue": 68_00_000, "cogs": 19_00_000,
                 "gross_margin": 49_00_000, "opex": 34_00_000, "net_income": 15_00_000},
                {"month": "2026-02", "revenue": 72_50_000, "cogs": 20_00_000,
                 "gross_margin": 52_50_000, "opex": 35_50_000, "net_income": 17_00_000},
                {"month": "2026-03", "revenue": 78_00_000, "cogs": 21_50_000,
                 "gross_margin": 56_50_000, "opex": 37_00_000, "net_income": 19_50_000},
            ],
            "bank_balances": [
                {"account": "HDFC Current A/c", "balance": 1_45_00_000, "currency": "INR"},
                {"account": "ICICI Savings A/c", "balance": 62_00_000, "currency": "INR"},
                {"account": "SBI FD", "balance": 50_00_000, "currency": "INR"},
                {"account": "Wise USD A/c", "balance": 48_500, "currency": "USD"},
            ],
            "pending_approvals_count": 7,
            "tax_calendar": [
                {"filing": "GST-3B (March)", "due_date": "2026-04-20", "status": "pending"},
                {"filing": "TDS 26Q (Q4)", "due_date": "2026-05-15", "status": "upcoming"},
                {"filing": "Advance Tax Q1", "due_date": "2026-06-15", "status": "upcoming"},
                {"filing": "ROC Annual Filing", "due_date": "2026-09-30", "status": "upcoming"},
            ],
        }

    @staticmethod
    def _fetch_cmo_kpis(company_id: str) -> dict[str, Any]:
        """Return CMO KPI data.  Mirrors ``api/v1/kpis.py`` demo payload."""
        return {
            "cac": 3_200,
            "cac_trend": -8.5,
            "mqls": 284,
            "mqls_trend": 12.3,
            "sqls": 67,
            "sqls_trend": 9.1,
            "pipeline_value": 1_42_00_000,
            "pipeline_trend": 15.6,
            "roas_by_channel": {
                "Google Ads": 4.2,
                "Meta Ads": 3.1,
                "LinkedIn": 2.8,
                "Organic": 7.6,
            },
            "email_performance": {
                "open_rate": 34.2,
                "click_rate": 4.8,
                "unsubscribe_rate": 0.3,
            },
            "social_engagement": {
                "Twitter": 12_400,
                "LinkedIn": 8_900,
                "Instagram": 15_600,
            },
            "website_traffic": {
                "sessions": 48_200,
                "users": 31_500,
                "bounce_rate": 42.1,
                "sessions_trend": [
                    {"date": "2026-03-01", "sessions": 1_420},
                    {"date": "2026-03-04", "sessions": 1_580},
                    {"date": "2026-03-07", "sessions": 1_350},
                    {"date": "2026-03-10", "sessions": 1_720},
                    {"date": "2026-03-13", "sessions": 1_890},
                    {"date": "2026-03-16", "sessions": 1_640},
                    {"date": "2026-03-19", "sessions": 2_010},
                    {"date": "2026-03-22", "sessions": 1_950},
                    {"date": "2026-03-25", "sessions": 2_200},
                    {"date": "2026-03-28", "sessions": 2_350},
                ],
            },
            "content_top_pages": [
                {"page": "/blog/ai-virtual-employees-guide", "views": 4_820, "avg_time_sec": 245},
                {"page": "/blog/automate-accounts-payable", "views": 3_150, "avg_time_sec": 198},
                {"page": "/pricing", "views": 2_900, "avg_time_sec": 130},
                {"page": "/blog/gst-compliance-automation", "views": 2_340, "avg_time_sec": 210},
                {"page": "/case-studies/enterprise-roi", "views": 1_870, "avg_time_sec": 310},
            ],
            "brand_sentiment_score": 78,
            "brand_sentiment_trend": 3.2,
            "pending_content_approvals": 4,
        }
