"""Report renderers — PDF (fpdf2) and Excel (openpyxl).

Both functions accept a ``ReportOutput`` and an output path, write the
file, and return the path for downstream delivery.
"""

from __future__ import annotations

from datetime import UTC, datetime
from typing import Any

from core.reports.generator import ReportOutput

# ══════════════════════════════════════════════════════════════════════
# PDF renderer (fpdf2)
# ══════════════════════════════════════════════════════════════════════

def render_pdf(report: ReportOutput, output_path: str) -> str:
    """Render *report* as a professional PDF document.

    Layout
    ------
    - Header band with AO branding, report title, and date.
    - KPI summary cards (extracted from ``content_data``).
    - Data tables with borders and alternating row colours.
    - Footer with "Generated by AgenticOrg" and timestamp.
    """
    from fpdf import FPDF  # fpdf2

    class _AO_PDF(FPDF):  # noqa: N801
        """Custom FPDF subclass with AgenticOrg header/footer."""

        def __init__(self, title: str, generated_at: str) -> None:
            super().__init__(orientation="P", unit="mm", format="A4")
            self._ao_title = title
            self._ao_generated = generated_at

        # ── Header ───────────────────────────────────────────────
        def header(self) -> None:
            # Logo placeholder — gradient-like coloured rectangle
            self.set_fill_color(59, 130, 246)  # blue-500
            self.rect(10, 8, 12, 12, style="F")
            self.set_fill_color(139, 92, 246)  # purple-600
            self.rect(16, 8, 6, 12, style="F")
            self.set_font("Helvetica", "B", 10)
            self.set_text_color(255, 255, 255)
            self.set_xy(11, 11)
            self.cell(10, 6, "AO", align="C")

            # Title
            self.set_text_color(30, 41, 59)
            self.set_font("Helvetica", "B", 14)
            self.set_xy(26, 8)
            self.cell(0, 7, self._ao_title)

            # Date subtitle
            self.set_font("Helvetica", "", 9)
            self.set_text_color(100, 116, 139)
            self.set_xy(26, 15)
            self.cell(0, 5, self._ao_generated)

            self.ln(16)

        # ── Footer ───────────────────────────────────────────────
        def footer(self) -> None:
            self.set_y(-15)
            self.set_font("Helvetica", "I", 8)
            self.set_text_color(148, 163, 184)
            footer = f"AgenticOrg | {self._ao_generated} | Page {self.page_no()}/{{nb}}"
            self.cell(0, 10, footer, align="C")

    generated_at = report.generated_at or datetime.now(UTC).isoformat()

    pdf = _AO_PDF(
        title=_report_type_label(report.report_type),
        generated_at=generated_at,
    )
    pdf.alias_nb_pages()
    pdf.set_auto_page_break(auto=True, margin=20)
    pdf.add_page()

    data = report.content_data

    # ── KPI cards ────────────────────────────────────────────────
    kpi_items = _extract_kpi_items(report.report_type, data)
    if kpi_items:
        _pdf_kpi_row(pdf, kpi_items)

    # ── Data tables extracted from content_data ──────────────────
    tables = _extract_tables(report.report_type, data)
    for tbl_title, headers, rows in tables:
        pdf.ln(4)
        pdf.set_font("Helvetica", "B", 11)
        pdf.set_text_color(30, 41, 59)
        pdf.cell(0, 8, tbl_title, ln=True)
        _pdf_table(pdf, headers, rows)

    pdf.output(output_path)
    return output_path


def _report_type_label(report_type: str) -> str:
    labels: dict[str, str] = {
        "cfo_daily": "CFO Daily Briefing",
        "cmo_weekly": "CMO Weekly Report",
        "aging_report": "AR/AP Aging Report",
        "pnl_report": "Profit & Loss Report",
        "campaign_report": "Campaign Performance Report",
        "shadow_reconciliation": "Shadow Reconciliation Report",
    }
    return labels.get(report_type, report_type.replace("_", " ").title())


def _pdf_kpi_row(pdf: Any, items: list[tuple[str, str, float | None]]) -> None:
    """Draw a horizontal row of KPI cards."""
    card_w = min(38, (190 - 4 * (len(items) - 1)) / max(len(items), 1))
    start_x = pdf.get_x()
    start_y = pdf.get_y()

    for i, (label, value, trend) in enumerate(items):
        x = start_x + i * (card_w + 4)
        pdf.set_xy(x, start_y)

        # Card background
        pdf.set_fill_color(248, 250, 252)
        pdf.set_draw_color(226, 232, 240)
        pdf.rect(x, start_y, card_w, 20, style="DF")

        # Label
        pdf.set_xy(x + 2, start_y + 2)
        pdf.set_font("Helvetica", "", 7)
        pdf.set_text_color(100, 116, 139)
        pdf.cell(card_w - 4, 4, label[:18], ln=False)

        # Value
        pdf.set_xy(x + 2, start_y + 7)
        pdf.set_font("Helvetica", "B", 11)
        pdf.set_text_color(30, 41, 59)
        pdf.cell(card_w - 4, 6, value[:16], ln=False)

        # Trend
        if trend is not None:
            pdf.set_xy(x + 2, start_y + 14)
            pdf.set_font("Helvetica", "", 7)
            if trend >= 0:
                pdf.set_text_color(22, 163, 74)
                pdf.cell(card_w - 4, 4, f"+{trend:.1f}%", ln=False)
            else:
                pdf.set_text_color(220, 38, 38)
                pdf.cell(card_w - 4, 4, f"{trend:.1f}%", ln=False)

    pdf.set_y(start_y + 24)


def _pdf_table(pdf: Any, headers: list[str], rows: list[list[str]]) -> None:
    """Draw a table with header row and alternating row colours."""
    col_count = len(headers)
    col_w = 190.0 / max(col_count, 1)

    # Header
    pdf.set_font("Helvetica", "B", 9)
    pdf.set_fill_color(30, 41, 59)
    pdf.set_text_color(255, 255, 255)
    for h in headers:
        pdf.cell(col_w, 7, h[:24], border=1, fill=True)
    pdf.ln()

    # Rows
    pdf.set_font("Helvetica", "", 8)
    pdf.set_text_color(30, 41, 59)
    for idx, row in enumerate(rows):
        if idx % 2 == 0:
            pdf.set_fill_color(241, 245, 249)
        else:
            pdf.set_fill_color(255, 255, 255)
        for cell in row:
            pdf.cell(col_w, 6, str(cell)[:30], border=1, fill=True)
        pdf.ln()


# ══════════════════════════════════════════════════════════════════════
# Excel renderer (openpyxl)
# ══════════════════════════════════════════════════════════════════════

def render_excel(report: ReportOutput, output_path: str) -> str:
    """Render *report* as a formatted Excel workbook."""
    from openpyxl import Workbook
    from openpyxl.styles import Alignment, Border, Font, PatternFill, Side
    from openpyxl.utils import get_column_letter

    wb = Workbook()
    ws = wb.active
    assert ws is not None
    # Sheet titles cannot contain / \ * ? : [ ] characters.
    _safe_title = _report_type_label(report.report_type)
    for ch in r"\/[]*?:":
        _safe_title = _safe_title.replace(ch, "-")
    ws.title = _safe_title[:31]

    # ── Styles ───────────────────────────────────────────────────
    header_font = Font(name="Calibri", bold=True, size=14, color="1E293B")
    subtitle_font = Font(name="Calibri", size=10, color="64748B")
    kpi_label_font = Font(name="Calibri", size=9, color="64748B")
    kpi_value_font = Font(name="Calibri", bold=True, size=14, color="1E293B")
    table_header_font = Font(name="Calibri", bold=True, size=10, color="FFFFFF")
    table_header_fill = PatternFill(start_color="1E293B", end_color="1E293B", fill_type="solid")
    even_row_fill = PatternFill(start_color="F1F5F9", end_color="F1F5F9", fill_type="solid")
    thin_border = Border(
        left=Side(style="thin", color="E2E8F0"),
        right=Side(style="thin", color="E2E8F0"),
        top=Side(style="thin", color="E2E8F0"),
        bottom=Side(style="thin", color="E2E8F0"),
    )
    footer_font = Font(name="Calibri", italic=True, size=8, color="94A3B8")

    row_idx = 1
    data = report.content_data

    # ── Title ────────────────────────────────────────────────────
    ws.cell(row=row_idx, column=1, value=_report_type_label(report.report_type)).font = header_font
    row_idx += 1
    ws.cell(row=row_idx, column=1, value=report.generated_at).font = subtitle_font
    row_idx += 2

    # ── KPI cards (single row) ───────────────────────────────────
    kpi_items = _extract_kpi_items(report.report_type, data)
    if kpi_items:
        for col_offset, (label, value, trend) in enumerate(kpi_items, start=1):
            col_letter = get_column_letter(col_offset)
            cell_label = ws.cell(row=row_idx, column=col_offset, value=label)
            cell_label.font = kpi_label_font
            cell_value = ws.cell(row=row_idx + 1, column=col_offset, value=value)
            cell_value.font = kpi_value_font
            if trend is not None:
                trend_str = f"+{trend:.1f}%" if trend >= 0 else f"{trend:.1f}%"
                trend_cell = ws.cell(row=row_idx + 2, column=col_offset, value=trend_str)
                trend_cell.font = Font(
                    name="Calibri", size=9,
                    color="16A34A" if trend >= 0 else "DC2626",
                )
            ws.column_dimensions[col_letter].width = 22
        row_idx += 4

    # ── Data tables ──────────────────────────────────────────────
    tables = _extract_tables(report.report_type, data)
    for tbl_title, headers, rows in tables:
        ws.cell(row=row_idx, column=1, value=tbl_title).font = Font(
            name="Calibri", bold=True, size=11, color="1E293B",
        )
        row_idx += 1

        # Header row
        for col_offset, h in enumerate(headers, start=1):
            c = ws.cell(row=row_idx, column=col_offset, value=h)
            c.font = table_header_font
            c.fill = table_header_fill
            c.border = thin_border
            c.alignment = Alignment(horizontal="left")
        row_idx += 1

        # Data rows
        for r_offset, row in enumerate(rows):
            for col_offset, cell_val in enumerate(row, start=1):
                c = ws.cell(row=row_idx, column=col_offset, value=cell_val)
                c.border = thin_border
                c.font = Font(name="Calibri", size=9)
                if r_offset % 2 == 0:
                    c.fill = even_row_fill
            row_idx += 1

        row_idx += 1  # gap between tables

    # ── Footer ───────────────────────────────────────────────────
    row_idx += 1
    ws.cell(row=row_idx, column=1, value=f"Generated by AgenticOrg  |  {report.generated_at}").font = footer_font

    # Auto-size columns (best-effort).
    for col in ws.columns:
        max_len = 0
        col_letter = get_column_letter(col[0].column)
        for cell in col:
            if cell.value is not None:
                max_len = max(max_len, len(str(cell.value)))
        adjusted = min(max_len + 4, 40)
        ws.column_dimensions[col_letter].width = max(adjusted, ws.column_dimensions[col_letter].width or 10)

    wb.save(output_path)
    return output_path


# ══════════════════════════════════════════════════════════════════════
# Data extraction helpers (shared by both renderers)
# ══════════════════════════════════════════════════════════════════════

def _extract_kpi_items(
    report_type: str,
    data: dict[str, Any],
) -> list[tuple[str, str, float | None]]:
    """Return a list of (label, formatted_value, trend%) for the report type."""
    items: list[tuple[str, str, float | None]] = []

    if report_type == "cfo_daily":
        items = [
            ("Cash Runway", f"{data.get('cash_runway_months', 0):.1f} mo", data.get("cash_runway_trend")),
            ("Monthly Burn", _inr(data.get("burn_rate", 0)), data.get("burn_rate_trend")),
            ("DSO", f"{data.get('dso_days', 0)} days", data.get("dso_trend")),
            ("DPO", f"{data.get('dpo_days', 0)} days", data.get("dpo_trend")),
            ("Pending Approvals", str(data.get("pending_approvals_count", 0)), None),
        ]
    elif report_type == "cmo_weekly":
        items = [
            ("CAC", _inr(data.get("cac", 0)), data.get("cac_trend")),
            ("MQLs", str(data.get("mqls", 0)), data.get("mqls_trend")),
            ("SQLs", str(data.get("sqls", 0)), data.get("sqls_trend")),
            ("Pipeline Value", _inr(data.get("pipeline_value", 0)), data.get("pipeline_trend")),
            ("Brand Sentiment", str(data.get("brand_sentiment_score", 0)), data.get("brand_sentiment_trend")),
        ]
    elif report_type == "aging_report":
        ar = data.get("ar_aging", {})
        ap = data.get("ap_aging", {})
        ar_total = sum(ar.values())
        ap_total = sum(ap.values())
        items = [
            ("Total AR", _inr(ar_total), None),
            ("Total AP", _inr(ap_total), None),
            ("Net Position", _inr(ar_total - ap_total), None),
            ("DSO", f"{data.get('dso_days', 0)} days", None),
            ("DPO", f"{data.get('dpo_days', 0)} days", None),
        ]
    elif report_type == "pnl_report":
        totals = data.get("totals", {})
        rev = totals.get("revenue", 0)
        gm = totals.get("gross_margin", 0)
        ni = totals.get("net_income", 0)
        gm_pct = (gm / rev * 100) if rev else 0
        ni_pct = (ni / rev * 100) if rev else 0
        items = [
            ("Total Revenue", _inr(rev), None),
            ("Gross Margin", f"{gm_pct:.1f}%", None),
            ("Net Income", _inr(ni), None),
            ("Net Margin", f"{ni_pct:.1f}%", None),
        ]
    elif report_type == "campaign_report":
        items = [
            ("CAC", _inr(data.get("cac", 0)), data.get("cac_trend")),
            ("MQLs", str(data.get("mqls", 0)), data.get("mqls_trend")),
            ("SQLs", str(data.get("sqls", 0)), data.get("sqls_trend")),
            ("Pipeline", _inr(data.get("pipeline_value", 0)), data.get("pipeline_trend")),
        ]
    elif report_type == "shadow_reconciliation":
        items = [
            ("Shadow Agents", str(data.get("shadow_agents_active", 0)), None),
            ("Tasks Evaluated", f"{data.get('shadow_tasks_evaluated', 0):,}", None),
            ("Agreement Rate", f"{data.get('agreement_rate_pct', 0):.1f}%", None),
            ("Disagreements", str(data.get("disagreements", 0)), None),
            ("Escalations", str(data.get("escalations", 0)), None),
        ]

    return items


def _extract_tables(
    report_type: str,
    data: dict[str, Any],
) -> list[tuple[str, list[str], list[list[str]]]]:
    """Return list of (title, headers, rows) tuples for the report type."""
    tables: list[tuple[str, list[str], list[list[str]]]] = []

    if report_type == "cfo_daily":
        # Bank balances
        banks = data.get("bank_balances", [])
        tables.append((
            "Bank Balances",
            ["Account", "Balance"],
            [[b["account"], f"{b['currency']} {b['balance']:,.0f}"] for b in banks],
        ))
        # Tax calendar
        taxes = data.get("tax_calendar", [])
        tables.append((
            "Tax Calendar",
            ["Filing", "Due Date", "Status"],
            [[t["filing"], t["due_date"], t["status"].title()] for t in taxes],
        ))

    elif report_type == "cmo_weekly":
        roas = data.get("roas_by_channel", {})
        tables.append((
            "ROAS by Channel",
            ["Channel", "ROAS"],
            [[ch, f"{val:.1f}x"] for ch, val in roas.items()],
        ))
        email = data.get("email_performance", {})
        tables.append((
            "Email Performance",
            ["Metric", "Value"],
            [
                ["Open Rate", f"{email.get('open_rate', 0):.1f}%"],
                ["Click Rate", f"{email.get('click_rate', 0):.1f}%"],
                ["Unsubscribe Rate", f"{email.get('unsubscribe_rate', 0):.1f}%"],
            ],
        ))
        pages = data.get("content_top_pages", [])
        tables.append((
            "Top Content Pages",
            ["Page", "Views", "Avg Time"],
            [[p["page"], f"{p['views']:,}", f"{p['avg_time_sec']}s"] for p in pages],
        ))

    elif report_type == "aging_report":
        ar = data.get("ar_aging", {})
        ap = data.get("ap_aging", {})
        buckets = ["0-30 days", "31-60 days", "61-90 days", "90+ days"]
        ar_keys = ["0_30", "31_60", "61_90", "90_plus"]
        tables.append((
            "Accounts Receivable Aging",
            ["Bucket", "Amount"],
            [[b, _inr(ar.get(k, 0))] for b, k in zip(buckets, ar_keys, strict=False)]
            + [["Total", _inr(sum(ar.values()))]],
        ))
        tables.append((
            "Accounts Payable Aging",
            ["Bucket", "Amount"],
            [[b, _inr(ap.get(k, 0))] for b, k in zip(buckets, ar_keys, strict=False)]
            + [["Total", _inr(sum(ap.values()))]],
        ))

    elif report_type == "pnl_report":
        monthly = data.get("monthly_pl", [])
        rows = [
            [m["month"], _inr(m["revenue"]), _inr(m["cogs"]),
             _inr(m["gross_margin"]), _inr(m["opex"]), _inr(m["net_income"])]
            for m in monthly
        ]
        totals = data.get("totals", {})
        rows.append([
            "Total", _inr(totals.get("revenue", 0)), _inr(totals.get("cogs", 0)),
            _inr(totals.get("gross_margin", 0)), _inr(totals.get("opex", 0)),
            _inr(totals.get("net_income", 0)),
        ])
        tables.append((
            "Profit & Loss Statement",
            ["Month", "Revenue", "COGS", "Gross Margin", "OpEx", "Net Income"],
            rows,
        ))

    elif report_type == "campaign_report":
        roas = data.get("roas_by_channel", {})
        tables.append((
            "ROAS by Channel",
            ["Channel", "ROAS"],
            [[ch, f"{val:.1f}x"] for ch, val in roas.items()],
        ))
        social = data.get("social_engagement", {})
        tables.append((
            "Social Engagement",
            ["Platform", "Engagements"],
            [[p, f"{e:,}"] for p, e in social.items()],
        ))
        traffic = data.get("website_traffic", {})
        tables.append((
            "Website Traffic",
            ["Metric", "Value"],
            [
                ["Sessions", f"{traffic.get('sessions', 0):,}"],
                ["Users", f"{traffic.get('users', 0):,}"],
                ["Bounce Rate", f"{traffic.get('bounce_rate', 0):.1f}%"],
            ],
        ))

    return tables


def _inr(amount: int | float) -> str:
    """Format an Indian-rupee amount."""
    return f"INR {amount:,.0f}"
