steps:
  - name: gcr.io/cloud-builders/docker
    entrypoint: bash
    args:
      - -c
      - |
        docker pull ghcr.io/huggingface/text-embeddings-inference:cpu-1.7 && \
        docker tag ghcr.io/huggingface/text-embeddings-inference:cpu-1.7 $_IMAGE && \
        docker push $_IMAGE
substitutions:
  _IMAGE: asia-south1-docker.pkg.dev/perfect-period-305406/agenticorg/text-embeddings-inference:cpu-1.7
options:
  machineType: E2_HIGHCPU_8
timeout: 600s
