steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - Dockerfile.ui.cloudrun
      - -t
      - asia-south1-docker.pkg.dev/perfect-period-305406/agenticorg/agenticorg-ui-cloudrun:v1
      - .
images:
  - asia-south1-docker.pkg.dev/perfect-period-305406/agenticorg/agenticorg-ui-cloudrun:v1
options:
  machineType: E2_HIGHCPU_8
timeout: 1500s
