"""Partial unique index on prompt_templates for active rows only.

Revision ID: v483_prompt_template_partial_unique
Revises: v482_init_db_advisory_lock
Create Date: 2026-04-16

Session 5 Aishwarya TC-003: creating a template, deleting it, and then
creating another with the same name hits HTTP 409 "already exists". The
Python query filters on is_active=True but the DB UniqueConstraint on
(tenant_id, name, agent_type) does not — a soft-deleted row still
blocks the INSERT at the database layer, so the app can never reach
its idempotent-reuse path.

Fix: replace the full unique constraint with a Postgres partial unique
index that only applies to active rows. Deleted rows no longer occupy
the name space.
"""

from __future__ import annotations

from alembic import op

# Alembic identifiers — kept <=32 chars (alembic_version.version_num size).
revision = "v483_prompt_tpl_partial_uniq"
down_revision = "v482_init_db_advisory_lock"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Drop the existing full unique constraint if it exists. The name is
    # autogenerated by SQLAlchemy, so look it up defensively.
    op.execute(
        """
        DO $$
        DECLARE
            c record;
        BEGIN
            FOR c IN
                SELECT conname FROM pg_constraint
                WHERE conrelid = 'prompt_templates'::regclass
                  AND contype = 'u'
                  AND pg_get_constraintdef(oid) LIKE 'UNIQUE (tenant_id, name, agent_type)%'
            LOOP
                EXECUTE format('ALTER TABLE prompt_templates DROP CONSTRAINT %I', c.conname);
            END LOOP;
        END $$;
        """
    )

    # Partial unique index — only enforces uniqueness among active rows.
    op.execute(
        """
        CREATE UNIQUE INDEX IF NOT EXISTS
            ux_prompt_templates_tenant_name_type_active
        ON prompt_templates (tenant_id, name, agent_type)
        WHERE is_active = true;
        """
    )


def downgrade() -> None:
    op.execute(
        "DROP INDEX IF EXISTS ux_prompt_templates_tenant_name_type_active;"
    )
    # Best-effort restore of the old unique constraint. A conflict between
    # the previously-allowed rows and this strict constraint would fail;
    # callers should assess data state before downgrading in production.
    op.execute(
        """
        ALTER TABLE prompt_templates
        ADD CONSTRAINT prompt_templates_tenant_id_name_agent_type_key
        UNIQUE (tenant_id, name, agent_type);
        """
    )
